name: Pre-commit auto-update

on:
  # every monday at midnight
  schedule:
    - cron: "0 0 * * 1"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install hatch

      - uses: browniebroke/pre-commit-autoupdate-action@main

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
